apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qc70iz6dv-python-gitops
  description: This is GitOps manifest for qc70iz6dv-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: qc70iz6dv-python
    janus-idp.io/tekton: qc70iz6dv-python
    backstage.io/kubernetes-id: qc70iz6dv-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qc70iz6dv-python
