apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qc70iz6dv-python
  janus-idp.io/tekton: qc70iz6dv-python
  backstage.io/kubernetes-id: qc70iz6dv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qc70iz6dv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
